name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    python_version: "3.10"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version}}

    - name: Install dependencies
      run: |
        python3 -m pip install boto3==1.26.33

    - name: Run script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python src/write_csv_to_s3.py